<?php

return [
    'email' => [
        'title' => 'Opdater din e-mail',
        'updated' => 'Din e-mailadresse er blevet opdateret.',
    ],
    'password' => [
        'title' => 'Skift din adgangskode',
        'requirements' => 'Din nye adgangskode skal være på mindst 8 tegn.',
        'updated' => 'Din adgangskode er blevet opdateret.',
    ],
    'two_factor' => [
        'button' => 'Configure 2-Factor Authentication',
        'disabled' => 'Two-factor authentication has been disabled on your account. You will no longer be prompted to provide a token when logging in.',
        'enabled' => 'Two-factor authentication has been enabled on your account! From now on, when logging in, you will be required to provide the code generated by your device.',
        'invalid' => 'The token provided was invalid.',
        'setup' => [
            'title' => 'Opsætning af to-faktor-godkendelse',
            'help' => 'Kan ikke scanne koden? Indtast koden nedenfor',
            'field' => 'Indtast token',
        ],
        'disable' => [
            'title' => 'Disable two-factor authentication',
            'field' => 'Enter token',
        ],
    ],
];
